from enum import Enum


class BookingStatus(str, Enum):
    REQUESTED = "REQUESTED"

    REVIEWING = "REVIEWING"

    CUSTOMER_CONTACTED = "CUSTOMER_CONTACTED"

    QUOTATION_PREPARING = "QUOTATION_PREPARING"

    QUOTATION_SENT = "QUOTATION_SENT"

    WAITING_FOR_CUSTOMER = "WAITING_FOR_CUSTOMER"

    QUOTATION_ACCEPTED = "QUOTATION_ACCEPTED"

    ADVANCE_PAYMENT_PENDING = "ADVANCE_PAYMENT_PENDING"

    ADVANCE_PAID = "ADVANCE_PAID"

    PAYMENT_VERIFIED = "PAYMENT_VERIFIED"

    PRIEST_ASSIGNED = "PRIEST_ASSIGNED"

    CATERING_ASSIGNED = "CATERING_ASSIGNED"

    MATERIALS_READY = "MATERIALS_READY"

    CALENDAR_SHARED = "CALENDAR_SHARED"

    SERVICE_IN_PROGRESS = "SERVICE_IN_PROGRESS"

    SERVICE_COMPLETED = "SERVICE_COMPLETED"

    FINAL_PAYMENT_PENDING = "FINAL_PAYMENT_PENDING"

    COMPLETED = "COMPLETED"

    CANCELLED = "CANCELLED"