"""create_booking_table

Revision ID: 0469b2e1b595
Revises: 2df888a4c334
Create Date: 2026-07-16 16:42:29.990660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0469b2e1b595'
down_revision: Union[str, Sequence[str], None] = '2df888a4c334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_number', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('pooja_id', sa.UUID(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('booking_time', sa.Time(), nullable=False),
    sa.Column('participants', sa.Integer(), nullable=False),
    sa.Column('devotee_name', sa.String(length=150), nullable=False),
    sa.Column('devotee_mobile', sa.String(length=20), nullable=False),
    sa.Column('devotee_email', sa.String(length=255), nullable=True),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('booking_status', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pooja_id'], ['pooja.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['temple_id'], ['temple.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_booking_number'), 'booking', ['booking_number'], unique=True)
    op.create_index(op.f('ix_booking_user_id'), 'booking', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_user_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_booking_number'), table_name='booking')
    op.drop_table('booking')
    # ### end Alembic commands ###
