"""create_pooja_table

Revision ID: 2df888a4c334
Revises: efa51db78459
Create Date: 2026-07-16 15:42:43.332816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df888a4c334'
down_revision: Union[str, Sequence[str], None] = 'efa51db78459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pooja',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('priest_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('online_booking', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['priest_id'], ['priest.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['temple_id'], ['temple.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pooja_category_id'), 'pooja', ['category_id'], unique=False)
    op.create_index(op.f('ix_pooja_name'), 'pooja', ['name'], unique=False)
    op.create_index(op.f('ix_pooja_priest_id'), 'pooja', ['priest_id'], unique=False)
    op.create_index(op.f('ix_pooja_slug'), 'pooja', ['slug'], unique=True)
    op.create_index(op.f('ix_pooja_temple_id'), 'pooja', ['temple_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pooja_temple_id'), table_name='pooja')
    op.drop_index(op.f('ix_pooja_slug'), table_name='pooja')
    op.drop_index(op.f('ix_pooja_priest_id'), table_name='pooja')
    op.drop_index(op.f('ix_pooja_name'), table_name='pooja')
    op.drop_index(op.f('ix_pooja_category_id'), table_name='pooja')
    op.drop_table('pooja')
    # ### end Alembic commands ###
