"""create_catering_table

Revision ID: 3195993d9cde
Revises: a60f57740a9b
Create Date: 2026-07-17 16:56:29.359478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3195993d9cde'
down_revision: Union[str, Sequence[str], None] = 'a60f57740a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catering',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=True),
    sa.Column('pooja_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('service_type', sa.String(length=30), server_default='CATERING', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('menu_details', sa.Text(), nullable=True),
    sa.Column('price_per_person', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_people', sa.Integer(), server_default='1', nullable=False),
    sa.Column('maximum_people', sa.Integer(), nullable=True),
    sa.Column('is_vegetarian', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pooja_id'], ['pooja.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['temple_id'], ['temple.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catering_is_available'), 'catering', ['is_available'], unique=False)
    op.create_index(op.f('ix_catering_pooja_id'), 'catering', ['pooja_id'], unique=False)
    op.create_index(op.f('ix_catering_service_type'), 'catering', ['service_type'], unique=False)
    op.create_index(op.f('ix_catering_temple_id'), 'catering', ['temple_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catering_temple_id'), table_name='catering')
    op.drop_index(op.f('ix_catering_service_type'), table_name='catering')
    op.drop_index(op.f('ix_catering_pooja_id'), table_name='catering')
    op.drop_index(op.f('ix_catering_is_available'), table_name='catering')
    op.drop_table('catering')
    # ### end Alembic commands ###
