"""create_gallery_table

Revision ID: 3a5de343584c
Revises: 26ce990541b1
Create Date: 2026-07-17 13:17:06.830434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5de343584c'
down_revision: Union[str, Sequence[str], None] = '26ce990541b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=True),
    sa.Column('pooja_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pooja_id'], ['pooja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temple_id'], ['temple.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_pooja_id'), 'gallery', ['pooja_id'], unique=False)
    op.create_index(op.f('ix_gallery_temple_id'), 'gallery', ['temple_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_temple_id'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_pooja_id'), table_name='gallery')
    op.drop_table('gallery')
    # ### end Alembic commands ###
