"""create_kundli_table

Revision ID: c423ae36ab09
Revises: 3195993d9cde
Create Date: 2026-07-17 18:39:36.140429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c423ae36ab09'
down_revision: Union[str, Sequence[str], None] = '3195993d9cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kundli',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('priest_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('time_of_birth', sa.Time(), nullable=False),
    sa.Column('place_of_birth', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('service_type', sa.String(length=50), server_default='KUNDLI', nullable=False),
    sa.Column('request_status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('user_question', sa.Text(), nullable=True),
    sa.Column('report_url', sa.String(length=500), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['priest_id'], ['priest.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kundli_priest_id'), 'kundli', ['priest_id'], unique=False)
    op.create_index(op.f('ix_kundli_request_status'), 'kundli', ['request_status'], unique=False)
    op.create_index(op.f('ix_kundli_service_type'), 'kundli', ['service_type'], unique=False)
    op.create_index(op.f('ix_kundli_user_id'), 'kundli', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kundli_user_id'), table_name='kundli')
    op.drop_index(op.f('ix_kundli_service_type'), table_name='kundli')
    op.drop_index(op.f('ix_kundli_request_status'), table_name='kundli')
    op.drop_index(op.f('ix_kundli_priest_id'), table_name='kundli')
    op.drop_table('kundli')
    # ### end Alembic commands ###
