"""create_consultation_table

Revision ID: cf4dd928f80e
Revises: c423ae36ab09
Create Date: 2026-07-17 18:54:12.217852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4dd928f80e'
down_revision: Union[str, Sequence[str], None] = 'c423ae36ab09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('priest_id', sa.UUID(), nullable=True),
    sa.Column('kundli_id', sa.UUID(), nullable=True),
    sa.Column('consultation_type', sa.String(length=30), server_default='VIDEO', nullable=False),
    sa.Column('consultation_status', sa.String(length=30), server_default='PENDING', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('user_question', sa.Text(), nullable=True),
    sa.Column('meeting_url', sa.String(length=1000), nullable=True),
    sa.Column('meeting_id', sa.String(length=255), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('priest_notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kundli_id'], ['kundli.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['priest_id'], ['priest.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_consultation_status'), 'consultation', ['consultation_status'], unique=False)
    op.create_index(op.f('ix_consultation_consultation_type'), 'consultation', ['consultation_type'], unique=False)
    op.create_index(op.f('ix_consultation_kundli_id'), 'consultation', ['kundli_id'], unique=False)
    op.create_index(op.f('ix_consultation_priest_id'), 'consultation', ['priest_id'], unique=False)
    op.create_index(op.f('ix_consultation_scheduled_at'), 'consultation', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_consultation_user_id'), 'consultation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_user_id'), table_name='consultation')
    op.drop_index(op.f('ix_consultation_scheduled_at'), table_name='consultation')
    op.drop_index(op.f('ix_consultation_priest_id'), table_name='consultation')
    op.drop_index(op.f('ix_consultation_kundli_id'), table_name='consultation')
    op.drop_index(op.f('ix_consultation_consultation_type'), table_name='consultation')
    op.drop_index(op.f('ix_consultation_consultation_status'), table_name='consultation')
    op.drop_table('consultation')
    # ### end Alembic commands ###
